### ISSUE TITLE
You have to be inside an angular-cli project in order to use the serve command.

### ISSUE THREAD

**Issue by myoneray** [wangdicoder/angular-material-dashboard#3]
17:58:08 maixiao@MaiziMacBook-Pro.local angular-material-dashboard master ng serve -o
You are running version 6.0.0 of Node, which will not be supported in future
versions of the CLI. The official Node version that will be supported is 6.9 and greater.

To disable this warning use "ng set --global warnings.nodeDeprecation=false".
### 
You have to be inside an angular-cli project in order to use the serve command.
17:59:31 maixiao@MaiziMacBook-Pro.local angular-material-dashboard master

**Comment by wangdicoder** [comment]
This is the angular-cli version issue. Don't worry about that

**Comment by tryrefine** [comment]
npm install -g @angular/cli@latest

**Comment by tryrefine** [comment]
npm install -g @angular/cli@latest

**Comment by tryrefine** [comment]
"npm install -g @angular/cli@latest"

**Comment by tryrefine** [comment]
`npm install -g @angular/cli@latest`
