### ISSUE TITLE
Responsive Issue: Toggle Menu doesn't work when in mobile adaptive mode

### ISSUE THREAD

**Issue by ghostzali** [wangdicoder/angular-material-dashboard#4]
Responsive Issue: Toggle Menu doesn't work when in mobile adaptive mode.

> this is the preview
![angular-material-dashboard-responsive-issue](https://user-images.githubusercontent.com/4680012/29319039-b164f91a-81fc-11e7-8155-747406d593c7.png)

**Comment by wangdicoder** [comment]
Yes, I haven't achieved that function. Just done the responsive navigation layout
